title: A GitHub Website
author: GitHub User Forrest
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This website was made using Jekyll via GitHub Pages

# social links
github_username:  SpaceSapphic

show_excerpts: true # set to false to remove excerpts on the homepage
